# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: groupgram
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: groupgram
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: